### ISSUE TITLE
lodash missing _.merge after loading optimizely

### ISSUE THREAD

**Issue by dpix** [optimizely/node-sdk#55]
_This is an issue for me with the client sdk but the problem seems to stem from here._

Not sure quite what is going on, but after loading the client sdk, lodash is missing the `merge` function which is required in our app. 

I have setup a basic enough test where I:
* load the exact same version of lodash this project does into a page
* try use merge and it works fine.
* load the optimizely client sdk
* `_.merge is not a function`

index.js
```javascript
<html>
    <head>
        <script src="/node_modules/lodash/lodash.js"></script>
        <script>
            // works as expected
            _.merge(1, 2);
        </script>
        <script src="/node_modules/optimizely-client-sdk/dist/optimizely.min.js"></script>
        <script>
            // TypeError: _.merge is not a function
            _.merge(1, 2);
        </script>
    </head>
</html>
```
package.json
```javascript
{
  "name": "lodash-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "lodash": "^4.13.1",
    "optimizely-client-sdk": "^1.3.4"
  }
}
```

**Comment by mikeng13** [comment]
@dpix thanks for raising this issue. Will take a look get back to you when we get the chance!

**Comment by caitlinrubin-optimizely** [comment]
Hi @dpix -- I looked into it and I can't seem to reproduce your error using that code. We'll be bumping the version to 1.4.1 very soon, try it out with that version and see if the error persists!

**Comment by dpix** [comment]
Thanks @caitlinrubin-optimizely, looks like it's been fixed up in the last release 👍
