### ISSUE TITLE
Typescript types

### ISSUE THREAD

**Issue by avindra** [optimizely/node-sdk#63]
Hello friends,

Do you have any interest in publishing types for this package? It's a matter of generating the corresponding `.d.ts` files for the `.js` files and specifying a `typings` key in `package.json`.

I'm particularly interested in this for projects at work, and wonder if there's anyone else out there in the community who would want this feature.

**Comment by mikeng13** [comment]
@avindra thanks for reaching out. We don't currently yet have the bandwidth for such nice things =) Will revisit at a later date.

**Comment by ffMathy** [comment]
And what about now? 😄

**Comment by mikeng13** [comment]
@ffMathy we've deprecated this repo. Please check out this new repo/package, which contains the Typescript defs: https://github.com/optimizely/javascript-sdk

**Comment by ffMathy** [comment]
You should archive the repo here in GitHub to make the deprecation more clear.

**Comment by mikeng13** [comment]
You’re right! I’ll archive it to avoid further confusion.
