### ISSUE TITLE
Live variable support

### ISSUE THREAD

**Issue by avindra** [optimizely/node-sdk#65]
According to:

https://developers.optimizely.com/x/solutions/sdks/reference/index.html?language=node#variables

> Live variables are not yet generally released for our Node SDK and we'll be posting documentation shortly.

Is there a public roadmap we can use to track the progress of this feature? Definitely interested in using this if possible.

**Comment by mikeng13** [comment]
@avindra thanks for the interest. We will be starting work on variables in the coming weeks so stay tuned!

**Comment by mustafashabib** [comment]
👍 Any word on this feature?

**Comment by mikeng13** [comment]
I don't yet have a definitive time frame, but likely to be by the end of Q3 (October). Will keep y'all posted as we move closer towards the date.

**Comment by mikeng13** [comment]
Variable support will be available with our new Feature Management feature. YOu can find out more about it in this release: https://github.com/optimizely/javascript-sdk/releases/tag/v2.0.0-beta1. Note: we have merged this package with the JavaScript package as described in that release.
