### ISSUE TITLE
Duplicate key USER_NOT_IN_EXPERIMENT

### ISSUE THREAD

**Issue by Jud** [optimizely/node-sdk#71]
In `node-sdk/lib/utils/enums/index.js` the key `USER_NOT_IN_EXPERIMENT` is duplicated on lines 76 and 81.

https://github.com/optimizely/node-sdk/blob/8cb98614b209266cd013518b3710365db9fc6b01/lib/utils/enums/index.js#L76
https://github.com/optimizely/node-sdk/blob/8cb98614b209266cd013518b3710365db9fc6b01/lib/utils/enums/index.js#L81

This throws an error when running the minified build through closure compiler.

**Comment by mikeng13** [comment]
Thanks @Jud will look into this and fix.

**Comment by mikeng13** [comment]
@Jud the latest version, `1.3.3` has the fix for this issue. Please check it out!
