### ISSUE TITLE
Lodash loading

### ISSUE THREAD

**Issue by reintroducing** [optimizely/node-sdk#80]
Hello,
I was just looking our bundle over in the webpack-bundle-analyzer and I noticed that this SDK is loading its own version of Lodash (and the whole thing at that). In looking through some of your code, there are instances where you load just the method being used but in the main index file you're loading the whole library just to use `assign`. 

Is it possible to refactor your code to load only the parts of lodash that are being used to cut down on the bundled size of this module?  Here is a screenshot of your module in the analyzer: https://www.dropbox.com/s/t66gkntl54m93b4/Screenshot%202017-06-30%2010.43.12.png?dl=0

**Comment by caitlinrubin-optimizely** [comment]
Hi @reintroducing -- thanks for your suggestion. We'll implement that fix soon.

**Comment by reintroducing** [comment]
Thanks @caitlinrubin-optimizely for the quick reply! It may also be worth looking at peerDependencies so that in the event that the lodash modules are already in the bundle they aren't duplicated in your SDK as well.

**Comment by vedrani** [comment]
Or just add caret on semver for lodash `^4.13.1` that will allow installation in range `lodash@>=4.13.1 <5.0.0`

 `https://semver.npmjs.com/`

**Comment by reintroducing** [comment]
@caitlinrubin-optimizely any updates on this? we're once again trying to cut down our builds and still noticing this. I saw that the javascript-sdk fixed this (i think?) but this one still doesn't seem to be fixed (or at least not released). Please advise. Thanks.

**Comment by caitlinrubin-optimizely** [comment]
Hi @reintroducing - can you be more specific? Just did a once over and I don't see us requiring the entirety of lodash anymore (definitely not in the index file)

**Comment by reintroducing** [comment]
So it looks like the lodash issues here have been removed but when you install the javascript SDK its loading version 1.3.3 of this which i believe still had the old lodash imports in it. if you could please bump the version of optimizely-server-sdk used in javascript-sdk to this latest version than i would think it would fix the issue.

**Comment by caitlinrubin-optimizely** [comment]
Ah understood @reintroducing -- we'll be releasing js 1.5.0 soon so that fix will be coming out shortly -- thank you for your patience.

**Comment by mikeng13** [comment]
@reintroducing we've released JS 1.5.x along with the bumped version of the `optimizely-server-sdk`. This should fix the issue. I am going to close out.
