### ISSUE TITLE
Event tag 'revenue' allows float and numeric string - Is this correct?

### ISSUE THREAD

**Issue by oakbani** [optimizely/node-sdk#94]
https://github.com/optimizely/node-sdk/blob/master/lib/utils/event_tag_utils/index.js#L39

https://github.com/optimizely/node-sdk/blob/master/lib/utils/event_tag_utils/tests.js#L32-L37

**Comment by oakbani** [comment]
https://github.com/optimizely/node-sdk/blob/master/lib/utils/event_tag_utils/tests.js#L32-L37

**Comment by mikeng13** [comment]
Yes. We are making the APIs more flexible and will rely on verbose logging for the user to understand what is going on. We will also document this in our dev docs.
